---
env:
  contexts:
  - name: "Default Context"
    urls:
    - "http://zero.webappsecurity.com"
    includePaths:
    - "http://zero.webappsecurity.com.*"
    excludePaths: []
    authentication:
      method: "form"
      parameters:
        loginPageUrl: "http://zero.webappsecurity.com/signin.html"
        loginRequestUrl: "http://zero.webappsecurity.com/signin.html"
        loginRequestBody: "user_login={%username%}&user_password={%password%}&submit=Sign+in&user_token=64c2bd64-2277-4460-9130-0f5c099c09ea"
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: "cookie"
      parameters: {}
    technology:
      exclude: []
    users:
    - name: "username"
      credentials:
        password: "password"
        username: "username"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
    disableAllRules: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters:
    context: "Default Context"
    user: "username"
    url: "http://zero.webappsecurity.com/login.html"
    maxDuration: 0
    maxDepth: 0
    maxChildren: 0
  name: "spider"
  type: "spider"
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters:
    context: "Default Context"
    user: "username"
    url: "http://zero.webappsecurity.com/login.html"
    maxDuration: 60
    maxCrawlDepth: 10
    numberOfBrowsers: 16
    inScopeOnly: true
    runOnlyIfModern: true
  name: "spiderAjax"
  type: "spiderAjax"
  tests:
  - onFail: "INFO"
    statistic: "spiderAjax.urls.added"
    site: ""
    operator: ">="
    value: 100
    name: "At least 100 URLs found"
    type: "stats"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters:
    context: "Default Context"
    user: "username"
    policy: ""
    maxRuleDurationInMins: 0
    maxScanDurationInMins: 0
  policyDefinition:
    defaultStrength: "medium"
    defaultThreshold: "medium"
    rules: []
  name: "activeScan"
  type: "activeScan"
- parameters:
    template: "risk-confidence-html"
    reportDir: "C:\\Users\\MarkFe"
    reportTitle: "ZAP Scanning Report"
    reportDescription: ""
  name: "report"
  type: "report"

