---
env:
  contexts:
  - name: "Default Context"
    urls: ["http://zero.webappsecurity.com"]
    includePaths: []
    excludePaths: []
    authentication:
      method: "form"
      parameters:
        loginPageUrl: "http://zero.webappsecurity.com/login.html"
        loginRequestUrl: "http://zero.webappsecurity.com/login.html"
        loginRequestBody: "user_login={%username%}&user_password={%password%}&submit=Sign+in&user_token=64c2bd64-2277-4460-9130-0f5c099c09ea"
      verification:
        method: "response"
        pollFrequency: 60
        pollUnits: "requests"
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: "cookie"
      parameters: {}
    technology:
      exclude: []
    users:
    - name: "username"
      credentials:
        password: "password"
        username: "username"
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars: {}
jobs:
- parameters:
    scanOnlyInScope: true
    enableTags: false
  rules: []
  name: "passiveScan-config"
  type: "passiveScan-config"
- parameters: {}
  tests:
  - onFail: "INFO"
    statistic: "automation.spider.urls.added"
    #site: ""
    operator: ">="
    value: 1
    type: "stats"
    name: "At least 1 URL found"
  name: "spider"
  type: "spider"
- parameters: {}
  tests:
  - onFail: "INFO"
    statistic: "spiderAjax.urls.added"
    #site: ""
    operator: ">="
    value: 1
    type: "stats"
    name: "At least 1 URL found"
  name: "spiderAjax"
  type: "spiderAjax"
- parameters: {}
  name: "passiveScan-wait"
  type: "passiveScan-wait"
- parameters: {}
  policyDefinition:
    rules: []
  name: "activeScan"
  type: "activeScan"
- parameters:
    template: "traditional-pdf"
    reportDir: "C:\\ZAP CLI\\Reports"
    reportTitle: "ZAP Scanning Report"
    reportDescription: ""
  name: "report"
  type: "report"
